# Generated by Django 6.0.5 on 2026-06-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_projectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.CharField(
                choices=[
                    ('CC BY 4.0', 'CC BY 4.0'),
                    ('CC BY-SA 4.0', 'CC BY-SA 4.0'),
                    ('CC BY-NC 4.0', 'CC BY-NC 4.0'),
                    ('CC BY-ND 4.0', 'CC BY-ND 4.0'),
                    ('CC BY-NC-SA 4.0', 'CC BY-NC-SA 4.0'),
                    ('CC BY-NC-ND 4.0', 'CC BY-NC-ND 4.0'),
                    ('CC0 1.0', 'CC0 1.0'),
                    ('Unlicense', 'Unlicense'),
                    ('MIT', 'MIT'),
                    ('CERN-OHL-S-2.0', 'CERN-OHL-S-2.0'),
                    ('All Rights Reserved', 'All Rights Reserved'),
                ],
                default='CC BY-SA 4.0',
                max_length=50,
            ),
        ),
    ]
