# Generated by Django 6.0.5 on 2026-06-21 20:07

from django.db import migrations, models


def migrate_all_rights_reserved(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Project.objects.filter(license='All Rights Reserved').update(license='CC BY-SA 4.0')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_expand_license_choices'),
    ]

    operations = [
        migrations.RunPython(migrate_all_rights_reserved, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.CharField(
                choices=[
                    ('CC BY 4.0', 'CC BY 4.0'),
                    ('CC BY-SA 4.0', 'CC BY-SA 4.0'),
                    ('CC BY-NC 4.0', 'CC BY-NC 4.0'),
                    ('CC BY-ND 4.0', 'CC BY-ND 4.0'),
                    ('CC BY-NC-SA 4.0', 'CC BY-NC-SA 4.0'),
                    ('CC BY-NC-ND 4.0', 'CC BY-NC-ND 4.0'),
                    ('CC0 1.0', 'CC0 1.0'),
                    ('Unlicense', 'Unlicense (Public Domain)'),
                    ('MIT', 'MIT'),
                    ('CERN-OHL-S-2.0', 'CERN-OHL-S-2.0'),
                ],
                default='CC BY-SA 4.0',
                max_length=50,
            ),
        ),
    ]
