# Generated by Django 6.0.5 on 2026-06-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_remove_all_rights_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='board_preview_bottom',
            field=models.FileField(blank=True, upload_to='previews/'),
        ),
        migrations.AddField(
            model_name='project',
            name='board_preview_top',
            field=models.FileField(blank=True, upload_to='previews/'),
        ),
    ]
